### ISSUE TITLE
How to add a New profile?

### ISSUE THREAD

**Issue by prats84** [google/rekall-profiles#35]
Is there a documentation to add new profiles to the local cache folder and to this repository ?

For Eg. I have created a Ubuntu profile on the machine but GRR is unable to pick that up. It comes back with the error profile not found. 

Is there a way to add the new profiles in the index.gz and place them in a particular rekall_profile/Linux/Ubuntu folder or something ?

**Comment by prats84** [comment]
We can make a pull request to submit it here.. but I am unsure on which files in the repo needs to ge t updated.

**Comment by scudette** [comment]
You need to add the profiles into the src/ directory and then run the rekall manage_repo plugin to rebuild all indexes.

If you would like to send a PR, please only include the files in the src/ directory. Thanks :-)

**Comment by prats84** [comment]
Thanks.
