### ISSUE TITLE
Requesting generation and repo integration of profile fur GUID 71935926C8684A2395F3BBE58FA587E61

### ISSUE THREAD

**Issue by elechon** [google/rekall-profiles#36]
Hi everyone,

it would be awesome if you could add a working profile for GUID 71935926C8684A2395F3BBE58FA587E61 (Windows 10 10.0.15063SP0) to this repo. I already tried my luck going through the standard MS pdb based generation process but the generated profile (see attachment) seems to lack important structures that I am not able identify and fix myself.

Thanks a lot for your help!

Cheers,
Tobias

[71935926C8684A2395F3BBE58FA587E61.gz](https://github.com/google/rekall-profiles/files/1711423/71935926C8684A2395F3BBE58FA587E61.gz)

**Comment by scudette** [comment]
I tried to go through the standard pdb generation and it seems to work now. I wonder if sometimes MS will publish a broken pdb file and then realize their mistake fix it later?

**Comment by elechon** [comment]
That is indeed very strange. Thanks a lot for pushing the new profile!
