### ISSUE TITLE
Help me :(

### ISSUE THREAD

**Issue by Isaac12-12** [google/rekall-profiles#50]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\Program Files\Rekall\rekall\session.pyc in __getitem__(self, item)

KeyError: 'imageinfo'

During handling of the above exception, another exception occurred:

error                                     Traceback (most recent call last)
C:\Program Files\Rekall\rekall\plugins\addrspaces\win32.pyc in _OpenFileForRead(self, path)

error: (2, 'CreateFile', '지정된 파일을 찾을 수 없습니다.(The specified file could not be found.)')

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
C:\Program Files\Rekall\IPython\core\prefilter.pyc in prefilter_lines(self, lines, continue_prompt)

C:\Program Files\Rekall\IPython\core\prefilter.pyc in prefilter_line(self, line, continue_prompt)

C:\Program Files\Rekall\IPython\core\prefilter.pyc in prefilter_line_info(self, line_info)

C:\Program Files\Rekall\IPython\core\prefilter.pyc in find_handler(self, line_info)

C:\Program Files\Rekall\IPython\core\prefilter.pyc in check(self, line_info)

C:\Program Files\Rekall\rekall\session.pyc in get(self, item, default)

C:\Program Files\Rekall\rekall\session.pyc in __getitem__(self, item)

C:\Program Files\Rekall\rekall\session.pyc in __getattr__(self, name)

C:\Program Files\Rekall\rekall\session.pyc in GetPluginClass(self, name)

C:\Program Files\Rekall\rekall\plugin.pyc in GetActivePlugin(self, plugin_name)

C:\Program Files\Rekall\rekall\plugin.pyc in is_active(cls, session)

C:\Program Files\Rekall\rekall_lib\utils.pyc in __get__(self, *args, **kwargs)

C:\Program Files\Rekall\rekall\session.pyc in profile(self)

C:\Program Files\Rekall\rekall\session.pyc in GetParameter(self, item, default, cached)

C:\Program Files\Rekall\rekall\session.pyc in _RunParameterHook(self, name)

C:\Program Files\Rekall\rekall\plugins\guess_profile.pyc in calculate(self)

C:\Program Files\Rekall\rekall\plugins\core.pyc in GetPhysicalAddressSpace(self)

C:\Program Files\Rekall\rekall\plugins\core.pyc in GuessAddressSpace(self, base_as, **kwargs)

C:\Program Files\Rekall\rekall_lib\registry.pyc in __call__(cls, *args, **kwargs)

C:\Program Files\Rekall\rekall\plugins\addrspaces\win32.pyc in __init__(self, base, filename, **kwargs)

C:\Program Files\Rekall\rekall\plugins\addrspaces\win32.pyc in _OpenFileForRead(self, path)

OSError: Unable to open .\DESKTOP-V8T2BTH-20201020-015608.raw: (2, 'CreateFile', '지정된 파일을 찾을 수 없습니다.(The specified file could not be found.)')

**Comment by Isaac12-12** [comment]
These errors occur when you use the plug-in in Recall. 
What should I do if I try to print out the plug-in normally?

**Comment by joachimmetz** [comment]
@Isaac12-12 FYI this project is discontinued https://github.com/google/rekall-profiles/blob/gh-pages/README.md#rekall-discontinuation. I'll be closing this issue and archiving the project.
